logging:
  file:
    name: /home/rahul/sadguru.log

  level:
    org:
      apache:
        http: INFO

bezkoder:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: bezKoderSecretKey
info:
  app:
    description: Spring Boot - RestTemplate CRUD Rest Client Example
    name: Spring Boot - RestTemplate CRUD Rest Client Example
    version: 1.0.0
server:
  port: 8088
spring:
  datasource:
    password: Vidula@9975
#    url: jdbc:mysql://localhost:3306/sadguru_DB?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:postgresql://localhost:5432/sadguru_db?currentSchema=public
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
#        driverClassName: com.mysql.cj.jdbc.Driver
        driverClassName: org.postgresql.Driver
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: SHREE-SADGURU-NATURAL-FRONT-END-PRODUCTS
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

